apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - install.yaml
  - image-updater-install.yaml

patches:
  - path: image-updater-config-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-image-updater-config
