apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  SPRING__APPLICATION__NAME: "inventory-service"
  SPRING__CLOUD__CONFIG__URI: "http://config-server:8888"
  SPRING__CLOUD__CONFIG__FAILFAST: "false"
  Consul__Host: "http://consul-server:8500"
---

