---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5020
      targetPort: 5020
      protocol: TCP
      name: http
  selector:
    app: inventory-service
---

