# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: consul
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   project: default
#   source:
#     repoURL: https://helm.releases.hashicorp.com
#     chart: consul
#     targetRevision: 1.5.3
#     helm:
#       releaseName: consul
#       valueFiles:
#         - $values/helm/consul/custom-values.yaml
#   sources:
#     - repoURL: https://helm.releases.hashicorp.com
#       chart: consul
#       targetRevision: 1.5.3
#     - repoURL: https://github.com/konecta-org/konectaerp-infra.git
#       targetRevision: HEAD
#       ref: values
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: consul
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
