---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: default
  labels:
    app: user-management-service
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5078
      targetPort: 5078
      protocol: TCP
      name: http
  selector:
    app: user-management-service
---

