# Base kustomization file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: default

resources:
  # Infrastructure
  - sqlserver/secret.yaml
  - sqlserver/pvc.yaml
  - sqlserver/statefulset.yaml
  - sqlserver/service.yaml
  - sqlserver/configmap.yaml
  - sqlserver/seed-job.yaml

  - rabbitmq/secret.yaml
  - rabbitmq/pvc.yaml
  - rabbitmq/statefulset.yaml
  - rabbitmq/service.yaml

  - mailhog/deployment.yaml
  - mailhog/service.yaml

  # Application services
  - config-server/configmap.yaml
  - config-server/deployment.yaml
  - config-server/service.yaml

  - api-gateway/configmap.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/hpa.yaml

  - authentication-service/configmap.yaml
  - authentication-service/deployment.yaml
  - authentication-service/service.yaml
  - authentication-service/hpa.yaml

  - hr-service/configmap.yaml
  - hr-service/deployment.yaml
  - hr-service/service.yaml
  - hr-service/hpa.yaml

  - inventory-service/configmap.yaml
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
  - inventory-service/hpa.yaml

  - finance-service/configmap.yaml
  - finance-service/deployment.yaml
  - finance-service/service.yaml
  - finance-service/hpa.yaml

  - user-management-service/configmap.yaml
  - user-management-service/deployment.yaml
  - user-management-service/service.yaml
  - user-management-service/hpa.yaml

  - reporting-service/configmap.yaml
  - reporting-service/deployment.yaml
  - reporting-service/service.yaml
  - reporting-service/hpa.yaml

  - frontend/service.yaml
  - frontend/deployment.yaml
  - frontend/hpa.yaml

  # # Monitoring
  # - prometheus
  # - grafana

  # Networking
  - networking/ingress.yaml
  - networking/certificate.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: konecta-erp
