apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - namespace.yaml

# namePrefix: staging-

labels:
  - includeSelectors: true
    pairs:
      environment: staging

# Image tags for staging environment
images:
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/config-server
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/api-gateway
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/authentication-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/hr-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/inventory-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/finance-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/user-management-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/reporting-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/erp-system-478020/konecta-erp/frontend
    newTag: staging-latest

configMapGenerator:
  - literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    name: environment-config

generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: patch-resources.yaml
  - path: patch-hpa.yaml
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
